services:
  raster-resampling-app:
    build:
      context: ./raster-resampling-app
    volumes:
      - ./raster-resampling-app/input:/data/input
      - ./raster-resampling-app/output:/data/output
    environment:
      - INPUT_FILENAME=
      - TARGET_RES=100
      - RESAMPLE_ALG=near